// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v5.29.6
// source: src/proto/auth/auth.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth";

export interface Empty {
}

export interface AuthenticatedSessionResponse {
  session: Session | undefined;
  user: User | undefined;
}

export interface User {
  id: string;
  emailVerified: boolean;
  username: string;
  name: string;
  email?: string | undefined;
  image?: string | undefined;
  bio?: string | undefined;
  gender?: string | undefined;
  followersCount: number;
  followingCount: number;
  postsCount: number;
  lastActiveAt?: string | undefined;
  createdAt: string;
  updatedAt: string;
}

export interface UpdateUserRequest {
  username?: string | undefined;
  name?: string | undefined;
  image?: string | undefined;
  bio?: string | undefined;
  gender?: string | undefined;
  followersCount?: number | undefined;
  followingCount?: number | undefined;
  postsCount?: number | undefined;
  lastActiveAt?: string | undefined;
}

export interface UpdateUserResponse {
  status: boolean;
}

export interface Session {
  id: string;
  userId: string;
  expiresAt: string;
  token: string;
  ipAddress?: string | undefined;
  userAgent?: string | undefined;
  createdAt: string;
  updatedAt: string;
}

export interface PermissionSet {
  permissions: { [key: string]: ActionList };
}

export interface PermissionSet_PermissionsEntry {
  key: string;
  value: ActionList | undefined;
}

export interface ActionList {
  actions: string[];
}

export interface HasPermissionResponse {
  success: boolean;
}

export const AUTH_PACKAGE_NAME = "auth";

export interface AuthServiceClient {
  authenticate(request: Empty, metadata: Metadata, ...rest: any): Observable<AuthenticatedSessionResponse>;

  hasPermission(request: PermissionSet, metadata: Metadata, ...rest: any): Observable<HasPermissionResponse>;

  updateUser(request: UpdateUserRequest, metadata: Metadata, ...rest: any): Observable<UpdateUserResponse>;
}

export interface AuthServiceController {
  authenticate(
    request: Empty,
    metadata: Metadata,
    ...rest: any
  ): Promise<AuthenticatedSessionResponse> | Observable<AuthenticatedSessionResponse> | AuthenticatedSessionResponse;

  hasPermission(
    request: PermissionSet,
    metadata: Metadata,
    ...rest: any
  ): Promise<HasPermissionResponse> | Observable<HasPermissionResponse> | HasPermissionResponse;

  updateUser(
    request: UpdateUserRequest,
    metadata: Metadata,
    ...rest: any
  ): Promise<UpdateUserResponse> | Observable<UpdateUserResponse> | UpdateUserResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["authenticate", "hasPermission", "updateUser"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
