FROM node:lts-alpine

WORKDIR /app

RUN npm install -g turbo

COPY package*.json turbo.json ./

COPY apps/auth ./apps/auth

COPY packages ./packages

RUN npm ci

EXPOSE 3000

CMD ["npm", "run", "dev"]