{{- if .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gigglegram-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: gigglegram-prod
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - http:
        paths:
          {{- range .Values.expose }}
          - path: {{ .path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .name }}
                port:
                  number: {{ .service.port }}
          {{- end }}
{{- end }}