# PostgreSQL configuration
pg:
  name: pg
  replicaCount: 1
  image:
    repository: postgres
    tag: '17-alpine'
    pullPolicy: IfNotPresent
  secretName: pg-secret
  db:
    user: 'admin'
    name: 'gigglegram'
  service:
    port: 5432
    name: pg-svc
  storage:
    size: 5Gi
    storageClassName: 'standard'
# API
api:
  name: api
  replicaCount: 1
  image:
    repository: asia-southeast1-docker.pkg.dev/mystic-subject-478902-i5/gigglegram-api/api
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3001
# WEB
web:
  name: web
  replicaCount: 1
  image:
    repository: asia-southeast1-docker.pkg.dev/mystic-subject-478902-i5/gigglegram-web/web
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000