ingress: false
namespace: dev
# EXPOSING SERIVICES
expose:
  web:
    path: /*
    name: web
    service:
      port: 3000
  apiGateway:
    path: /api/*
    name: api-gateway
    service:
      port: 3001
  realTime:
    path: /socket.io/*
    name: real-time
    service:
      port: 3007
# APP SERVICES
apps:
  # API GATEWAY
  apiGateway:
    name: api-gateway
    replicaCount: 1
    image:
      repository: asia-southeast1-docker.pkg.dev/gigglegram-491420/api-gateway/prod
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      ports:
        - port: 3001
          name: http
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 4Gi
        cpu: 1
  # AUTH
  auth:
    name: auth
    replicaCount: 1
    image:
      repository: asia-southeast1-docker.pkg.dev/gigglegram-491420/auth/prod
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      ports:
        - port: 3002
          name: http
        - port: 5000
          name: grpc
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 4Gi
        cpu: 1
  # ENGAGEMENTS
  engagements:
    name: engagements
    replicaCount: 1
    image:
      repository: asia-southeast1-docker.pkg.dev/gigglegram-491420/engagements/prod
      tag: latest
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 4Gi
        cpu: 1
  # FEED
  feed:
    name: feed
    replicaCount: 1
    image:
      repository: asia-southeast1-docker.pkg.dev/gigglegram-491420/feed/prod
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      ports:
        - port: 3005
          name: http
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 4Gi
        cpu: 1
  # POSTS
  posts:
    name: posts
    replicaCount: 1
    image:
      repository: asia-southeast1-docker.pkg.dev/gigglegram-491420/posts/prod
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      ports:
        - port: 3003
          name: http
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 4Gi
        cpu: 1
  # REAL-TIME
  realTime:
    name: real-time
    replicaCount: 1
    image:
      repository: asia-southeast1-docker.pkg.dev/gigglegram-491420/real-time/prod
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      ports:
        - port: 3007
          name: http
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 4Gi
        cpu: 1
  # SETTINGS
  settings:
    name: settings
    replicaCount: 1
    image:
      repository: asia-southeast1-docker.pkg.dev/gigglegram-491420/settings/prod
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      ports:
        - port: 3004
          name: http
        - port: 5001
          name: grpc
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 4Gi
        cpu: 1
  # USERS
  users:
    name: users
    replicaCount: 1
    image:
      repository: asia-southeast1-docker.pkg.dev/gigglegram-491420/users/prod
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      ports:
        - port: 3006
          name: http
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 4Gi
        cpu: 1
  # WEB
  web:
    name: web
    replicaCount: 1
    image:
      repository: asia-southeast1-docker.pkg.dev/gigglegram-491420/web/prod
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      ports:
        - port: 3000
          name: http
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 4Gi
        cpu: 1
