// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.4
// source: src/proto/system-settings.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

const protobufPackage = "systemSettings";

export interface SettingKey {
  key: string;
}

export interface SettingPrefix {
  prefixes: string[];
}

export interface SystemSettingsResponse {
  settings: { [key: string]: SettingValue };
}

export interface SystemSettingsResponse_SettingsEntry {
  key: string;
  value: SettingValue | undefined;
}

export interface SettingValue {
  stringValue?: string | undefined;
  intValue?: number | undefined;
  floatValue?: number | undefined;
  boolValue?: boolean | undefined;
  jsonValue?: string | undefined;
}

export const SYSTEM_SETTINGS_PACKAGE_NAME = "systemSettings";

export interface SystemSettingsServiceClient {
  findSettingByKey(request: SettingKey, metadata: Metadata, ...rest: any): Observable<SettingValue>;

  findSettingsByPrefix(request: SettingPrefix, metadata: Metadata, ...rest: any): Observable<SystemSettingsResponse>;
}

export interface SystemSettingsServiceController {
  findSettingByKey(
    request: SettingKey,
    metadata: Metadata,
    ...rest: any
  ): Promise<SettingValue> | Observable<SettingValue> | SettingValue;

  findSettingsByPrefix(
    request: SettingPrefix,
    metadata: Metadata,
    ...rest: any
  ): Promise<SystemSettingsResponse> | Observable<SystemSettingsResponse> | SystemSettingsResponse;
}

export function SystemSettingsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["findSettingByKey", "findSettingsByPrefix"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("SystemSettingsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("SystemSettingsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SYSTEM_SETTINGS_SERVICE_NAME = "SystemSettingsService";
