{{- range .Values.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $.Values.namespace }}
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - containerPort: {{ .service.port }}
          volumeMounts:
            - name: secret-volume
              mountPath: "/app/apps/{{ .name }}/.env"
              subPath: .env
              readOnly: true
          # envFrom:
          #   - secretRef:
          #       name: gigglegram-secrets
          resources:
            requests:
              memory: {{ .resources.requests.memory }}
              cpu: {{ .resources.requests.cpu }}
            limits:
              memory: {{ .resources.limits.memory }}
              cpu: {{ .resources.limits.cpu }}
      volumes:
        - name: secret-volume
          secret:
            secretName: gigglegram-secrets
{{- end }}