{{- range .Values.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $.Values.namespace }}
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      serviceAccountName: {{ .serviceAccountName }}
      containers:
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          workingDir: /app/apps/{{ .name }}
          {{- if ne .name "web" }}
          command: ["node", "dist/main"]
          {{- end }}
          {{- if and .service .service.ports }}
          ports:
            {{- range .service.ports }}
            - containerPort: {{ .port }}
              name: {{ .name }}
            {{- end }}
          {{- end }}
          volumeMounts:
            - name: secret-volume
              {{- if eq .name "web" }}
              mountPath: "/app/apps/web/.env"
              subPath: .env
              {{- else }}
              mountPath: "/app/.env"
              subPath: .env
              {{- end }}
              readOnly: true
          # envFrom:
          #   - secretRef:
          #       name: gigglegram-secrets
          {{- if .readinessProbe }}
          readinessProbe:
            httpGet:
              path: {{ .readinessProbe.path }}
              port: {{ .readinessProbe.port }}
            initialDelaySeconds: {{ default 15 .readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ default 10 .readinessProbe.periodSeconds }}
            timeoutSeconds: {{ default 5 .readinessProbe.timeoutSeconds }}
            successThreshold: {{ default 1 .readinessProbe.successThreshold }}
            failureThreshold: {{ default 3 .readinessProbe.failureThreshold }}
          {{- end }}
          resources:
            requests:
              memory: {{ .resources.requests.memory }}
              cpu: {{ .resources.requests.cpu }}
            limits:
              memory: {{ .resources.limits.memory }}
              cpu: {{ .resources.limits.cpu }}
      volumes:
        - name: secret-volume
          secret:
            secretName: gigglegram-secrets
{{- end }}