{{- range .Values.apps }}
{{- if .service }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Values.namespace }}
  name: {{ .name }}
spec:
  type: {{ .service.type }}
  ports:
    {{- range .service.ports }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      name: {{ .name }}
    {{- end }}
  selector:
    app: {{ .name }}
{{- end }}
{{- end }}